# fly.toml app configuration file generated for hatchless-staging on 2025-12-21T15:14:47-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hatchless-staging'
primary_region = 'ord'

[processes]
  app = "bundle exec rails server -b 0.0.0.0 -p 3000"
  worker = "bundle exec rails solid_queue:start"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[statics]]
    guest_path = "/rails/public"
    url_prefix = "/"

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "bin/rails db:prepare"
